In [1]:
from bs4 import BeautifulSoup # this module helps in web scrapping.
import requests  # this module helps us to download a web page
import pandas as pd
# !pip install pandasql
from pandasql import sqldf
pysqldf = lambda q: sqldf(q, globals())

In [2]:
match_schedule_html = open('2022_t15_schedule_html.txt', 'r')
soup = BeautifulSoup(match_schedule_html, 'lxml')
match_schedule_html.close()

In [4]:
table = soup.select('table.schedtbl')[0]
table_df = pd.DataFrame()
table_df = pd.read_html(str(table))[0]
# table_df.drop(0, axis=0, inplace=True) # only drop first row if it contains default data
table_df.to_csv('2022_t15_schedule.csv', index=False)
table_df

,M,Date,Match,Venue No.,Location
0,1.0,Sat 16 Jul 2022,Brampton Rangers VS. Wildfiya Scorecard,1,Chinguacousy Secondary School 1370 Williams Pa...
1,2.0,Sat 16 Jul 2022,Phoenix 11 VS. Guycan Tridents Scorecard,24,B Field Hanover Public School 215 Hanover Road...
2,3.0,Sat 23 Jul 2022,Fuzion SC VS. Panthers Scorecard,14,"Marvin Heights Public school, 7455 Redstone Rd..."
3,4.0,Sat 23 Jul 2022,Pegasus VS. Cool Runningz Scorecard,45,A Field - Hanover Public School 215 Hanover Ro...
4,5.0,Sat 23 Jul 2022,11 Man Army VS. Masters Scorecard,22,"Dorset Public School. 100 Dorset Drive, Brampt..."
5,6.0,Sat 23 Jul 2022,Spartans VS. Wildfiya Scorecard,21,"Elia Middle School 215 Sentinel Rd, Toronto, ON."
6,7.0,Sat 23 Jul 2022,Brampton Gladiators VS. Smashers Scorecard,24,B Field Hanover Public School 215 Hanover Road...
7,8.0,Sat 23 Jul 2022,Enterprise VS. Tricounty Scorecard,41,"Grenoble PS, 33 Greenbriar Rd, Brampton, ON L6..."
8,9.0,Sat 23 Jul 2022,Aces Cricket Club VS. Industry CC Scorecard,26,"Dumbarton High School, 655 Sheppard Ave. Picke..."
9,10.0,Sat 23 Jul 2022,Paris Sunshine VS. Phoenix 11 Scorecard,43,"Robert J Lee Public School, 160 Mountainash Road"
10,11.0,Sat 06 Aug 2022,Pegasus VS. Enterprise Scorecard,45,A Field - Hanover Public School 215 Hanover Ro...
11,12.0,Sat 06 Aug 2022,Spartans VS. Aces Cricket Club Scorecard,21,"Elia Middle School 215 Sentinel Rd, Toronto, ON."
12,13.0,Sat 06 Aug 2022,Masters VS. Brampton Gladiators Scorecard,44,"Thackeray Park, 2955 Kipling Ave M5H 2N2"
13,14.0,Sat 06 Aug 2022,Paris Sunshine VS. Fuzion SC Scorecard,44,"Robert J Lee Public School, 160 Mountainash Ro..."
14,15.0,Sat 13 Aug 2022,Spartans VS. Pegasus Scorecard,21,"Elia Middle School 215 Sentinel Rd, Toronto, ON."
15,16.0,Sat 13 Aug 2022,Paris Sunshine VS. Masters Scorecard,43,"Robert J Lee Public School, 160 Mountainash Ro..."
16,17.0,Sat 20 Aug 2022,Masters VS. Pegasus Scorecard,31,"Andrew McCandless Park, 450 Elbern Markell Dr,..."

In [5]:
# SQL Query to Extract all Venues
q = """SELECT DISTINCT Location 
       FROM table_df;"""
venues = pysqldf(q)
venues

                                             Location
0   Chinguacousy Secondary School 1370 Williams Pa...
1   B Field Hanover Public School 215 Hanover Road...
2   Marvin Heights Public school, 7455 Redstone Rd...
3   A Field - Hanover Public School 215 Hanover Ro...
4   Dorset Public School. 100 Dorset Drive, Brampt...
5    Elia Middle School 215 Sentinel Rd, Toronto, ON.
6   Grenoble PS, 33 Greenbriar Rd, Brampton, ON L6...
7   Dumbarton High School, 655 Sheppard Ave. Picke...
8    Robert J Lee Public School, 160 Mountainash Road
9            Thackeray Park, 2955 Kipling Ave M5H 2N2
10  Robert J Lee Public School, 160 Mountainash Ro...
11  Andrew McCandless Park, 450 Elbern Markell Dr,...